version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: artesanias-postgres
    environment:
      POSTGRES_DB: artesanias_db
      POSTGRES_USER: artesanias_user
      POSTGRES_PASSWORD: artesanias_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
