# App
spring.application.name=artesanias-andreas-backend
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/artesanias_db
spring.datasource.username=artesanias_user
spring.datasource.password=artesanias_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable security default login (temporal)
spring.security.user.name=disabled
spring.security.user.password=disabled

